### ISSUE TITLE
Create a `nav` element in `index.html`

### ISSUE THREAD

**Issue by michaella23** [michaella23/bootcamp-collab#100]
For now this can just be a list of links, whatever you want to name them. When we have more `html` files added [issue #99], we will link to these. It's up to you if you want to make this `nav` responsive to different viewports.

**Comment by Pulkitxm** [comment]
Can I get assigned?

**Comment by michaella23** [comment]
@Pulkitxm I'm sorry, but we are only accepting contributions from [Scrimba Bootcamp](https://scrimba.com/bootcamp) students.

**Comment by ParthMadhvani2** [comment]
hey, I can complete this task so, can you please assign this task to me?

**Comment by michaella23** [comment]
@ParthMadhvani2 I'm sorry, but we are only accepting contributions from [Scrimba Bootcamp](https://scrimba.com/bootcamp) students.

**Comment by ajoborgvold** [comment]
@michaella23 I'm not sure about the workflow, so please let me know if I should do things differently. I've created a `nav` element and will make a pull request
