### ISSUE TITLE
[BUG] 'show more contributors' button does not get hidden and page crashes

### ISSUE THREAD

**Issue by michaella23** [michaella23/bootcamp-collab#102]
Take a look at the logic in `contributors-component.js` and debug. The 'load-more' button is not being hidden once all contributors are in view, and when clicked again the page crashes. Something might have been overlooked when refactoring and creating the `randomRender` function.

**Comment by will-s-205** [comment]
Sounds simple enough. Can I try?

**Comment by Kuanchiliao1** [comment]
Thanks! Leaving a comment here for assignment

**Comment by shantdashjian** [comment]
Issue is fixed. Closing.
