### ISSUE TITLE
[BUG]: theme button on 'About' page isn't working

### ISSUE THREAD

**Issue by michaella23** [michaella23/bootcamp-collab#111]
The theme button works correctly on the Home page, but not on the About page. Take a look to find out why and fix the issue.

**Comment by thezeeshann** [comment]
@michaella23 I would like to work on this issue. assign me.

**Comment by michaella23** [comment]
> @michaella23 I would like to work on this issue. assign me.

Hey there. We are currently only accepting contributions from [Scrimba Bootcamp](https://scrimba.com/bootcamp) students. Sorry.

**Comment by Kuanchiliao1** [comment]
Hey, may I please get assigned to this one? @michaella23

**Comment by michaella23** [comment]
> Hey, may I please get assigned to this one? @michaella23

I assigned it to you! I wasn't sure if you got a notification. No hurry. Thanks Tony.

**Comment by shantdashjian** [comment]
Issue fixed in PR: https://github.com/michaella23/bootcamp-collab/pull/116
