### ISSUE TITLE
add base.css to index.html

### ISSUE THREAD

**Issue by awcoetzer** [michaella23/bootcamp-collab#13]
index.html needs base.css in addition to index.css

**Comment by shantdashjian** [comment]
I don't think this is an issue. base.css is already imported in index.css and the styling in base.css gets applied to index.html merely by linking index.css in index.html.

**Comment by awcoetzer** [comment]
> I don't think this is an issue. base.css is already imported in index.css and the styling in base.css gets applied to index.html merely by linking index.css in index.html.

You are correct, apologies, will try and close this issue, not sure if I am able to.
Thank you again @shantdashjian

**Comment by awcoetzer** [comment]
Closing this issue as it's not needed.
