### ISSUE TITLE
Streamlining the issue process and promoting group work

### ISSUE THREAD

**Issue by awcoetzer** [michaella23/bootcamp-collab#18]
@michaella23 
Is there a way to see who is currently working on an open issue? 
I myself would love the opportunity to work alongside someone else who took on a specific issue considering the issue is something group worthy.

If this is not possible here on GitHub, maybe we can set up a channel in discord for bootcamp-callab and whenever an issue is made, to post it there and see who is up for the task and then assign them to the task. 
This might also open doors for multiple people who want to work on the issue and not only work together but to learn from each other as well. 
This could also help streamline the maintainers job when reviewing multiple solutions to issues. ( _not sure if that's thing_ )

**Comment by michaella23** [comment]
@awcoetzer as of now, I think only the maintainer can assign an issue. But anyone can comment on an issue and request to work on it. Then I can assign it to one or more people. If you have ideas for issues that would be ideal to work on with a group, please do create them! I love that idea.
Holding off on a separate Discord channel for now, it's something I have to ask the rest of the team about.

**Comment by awcoetzer** [comment]
> @awcoetzer as of now, I think only the maintainer can assign an issue. But anyone can comment on an issue and request to work on it. Then I can assign it to one or more people. If you have ideas for issues that would be ideal to work on with a group, please do create them! I love that idea. Holding off on a separate Discord channel for now, it's something I have to ask the rest of the team about.

Thank you @michaella23
