### ISSUE TITLE
[DOCS]: Add a license

### ISSUE THREAD

**Issue by michaella23** [michaella23/bootcamp-collab#42]
Reputable open source projects have a license, which gives users permissions to modify and contribute to the project. Read more about adding a license [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) and then choose the license you think is appropriate for our project. Please provide a short explanation about the license when submitting the PR.

**Comment by awcoetzer** [comment]
##### - GNU GPLv3
### If I had to pick one I would probably go for [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/).
_I don't know anything about licenses, so I went ahead and googled and found this site: [the 5 best open source licenses for securing your software rights](https://blog.zenhub.com/the-5-best-open-source-licenses-for-securing-your-software-rights/)_

##### - REASON FOR MY CHOICE
The GNU GPL is a copyleft license that ensures the software remains **free** and **open source**, allowing anyone to **view**, **modify**, and **distribute the code**.

Under the **GNU GPLv3**, if a student at Scrimba develops software and releases it under this license, it guarantees that the software and its derivatives will also be distributed under the same license. This means that anyone who receives the software can **access** the source code, **modify it**, and **distribute their modified version as long as they also distribute it under the GNU GPLv3**. This helps to ensure that the software **remains freely available** and that future improvements are contributed back to the community.

By choosing the **GNU GPLv3**, you are promoting the principles of open source software and fostering collaboration within the Scrimba community. It protects the rights of the developers and encourages the sharing of knowledge and advancements.

It's important to note that while the GNU GPLv3 allows free distribution, **it doesn't prevent others from making a profit by providing services related to the software**. For example, someone can charge for support or consulting services related to the software while still complying with the license.

In summary, the GNU GPLv3 is a **strong copyleft license** with strict distribution requirements, focusing on ensuring software freedom and promoting the open source nature of derived works.

##### - ADDITIONAL INFO

> Copyleft vs. permissive: The GNU GPLv3 is a copyleft license, while the MIT License is a permissive license. Copyleft licenses aim to ensure that derivative works and modifications of the original software remain under the same open source license. Permissive licenses, on the other hand, have fewer restrictions and allow the software to be used in proprietary projects without requiring those projects to be open source.

> License compatibility: The GNU GPLv3 is considered a strong copyleft license that is not compatible with some other licenses, particularly permissive ones. If you include GPL-licensed code in a project, the entire project typically needs to be licensed under the GPL as well. On the other hand, the MIT License is a permissive license that is compatible with most other open source licenses, giving you more flexibility in combining code from different projects with different licenses.

> Patents: The GNU GPLv3 includes specific clauses addressing patents, aiming to prevent patent holders from exerting control over users of the software. It provides explicit patent licensing provisions to ensure that users can freely use the software without fear of patent-related restrictions. The MIT License does not include such explicit patent provisions.

> Usage in commercial projects: While both licenses permit commercial use of the software, the GNU GPLv3 imposes restrictions on proprietary distribution. If you incorporate GPLv3-licensed code into a commercial project, you must make the entire project available under the GPL, including the source code. The MIT License allows you to use the code, modify it, and distribute it in commercial projects without being obligated to release the source code.
