### ISSUE TITLE
Random contributors on the front page

### ISSUE THREAD

**Issue by will-s-205** [michaella23/bootcamp-collab#73]
Issue ref: https://github.com/michaella23/bootcamp-collab/pull/67#issuecomment-1601730367
Right now we have a dropdown list of contributors and their references at the bottom of the front page. Dropdown works when contributors are more than 4. We want to fully randomize who shows up in the list as a first 4 contributors and who remains in dropdown.

![2023-06-21_15-18-55](https://github.com/michaella23/bootcamp-collab/assets/97144951/9a08e460-bce3-428f-923c-0dcad1bbd7c9)

**Comment by awcoetzer** [comment]
@will-s-205 I have fixed the issue

**Comment by will-s-205** [comment]
Thanks for letting me know @awcoetzer. I didn't know that you are working on that issue. Please make sure you added your branch to the project as a PR so it can be reviewed. Thank you.

**Comment by will-s-205** [comment]
Closing out this PR because it solved in PR below:
feat: 73 random contributors solved #78

**Comment by awcoetzer** [comment]
> Thanks for letting me know @awcoetzer. I didn't know that you are working on that issue. Please make sure you added your branch to the project as a PR so it can be reviewed. Thank you.

Yeah I was in the subway and saw your post here about having issues with duplicates and decided to take a quick look.

**Comment by awcoetzer** [comment]
I think the issue could still remain open as we can further implement other options.

Currently, we randomly load 6 contributors to the page, though on the next load it can load the same person but in a different position. I think if we utilize local storage to checkPreviousLoad, we can make it even more fair by not have the same person a refresh, if that makes sense.

**Comment by awcoetzer** [comment]
Awesome thank you

**Comment by awcoetzer** [comment]
Would anyone like to try and implement that?

**Comment by michaella23** [comment]
Glad to see some conversation here on this issue. I was a little confused to see two Pull Requests referencing this issue, and since no one requested to work on this issue per the new "General Guidelines" in CONTRIBUTING.md [ #65 ] not sure how best to proceed. Please let me know where we are at on this before I merge anything.
@will-s-205, did you look at the changed files in @awcoetzer's PR? Does this help to answer the questions you mentioned in your own PR? @awcoetzer, did you take a look at @will-s-205's PR? Do you have comments to add that might be helpful to anyone trying to understand how to get this code working?
Thank you both.

**Comment by will-s-205** [comment]
Yes, he did a great job by refactoring code lines. It is also an answer on my questions in Discord. Thanks

**Comment by awcoetzer** [comment]
Good morning from my side of the world! 😊☀️

Hello @michaella23, I noticed @will-s-205's code, and although I'm not sure how much more I can contribute, I believe there are several approaches to achieve the desired outcome, which is to check which contributors have been loaded.

One option is to add a specific value from the contributors object, such as their name or GitHub link, to a list. Alternatively, you can assign a unique ID to each contributor, especially if you have a backend system in place. Another approach is to use a Boolean value to determine whether a contributor has been loaded or not.

During my analysis, I encountered other issues within the for loop. When an object was skipped, it would still count as an iteration. To address this, I introduced a buffer variable. Although the buffer variable may not achieve the exact desired load amount, it ensures that the loop continues iterating, regardless of any skips. So, whenever there was a successful hit, the buffer would be incremented.

I find this problem to be both enjoyable and intriguing. I encourage others to participate as well. As mentioned earlier, we can expand on this problem by considering previous loads and ensuring that different contributors receive the spotlight upon refresh or subsequent visits.

For example, if Will, Micha, and Ali were loaded on the first page visit, this information should be logged somewhere and removed from the pool for the next refresh. Thus, on the second page load, they would not appear, and instead, new contributors would be displayed. However, the new contributors would replace the previously loaded contributors, who are now eligible to appear upon the next page refresh.

**Comment by will-s-205** [comment]
I'm closing my PR only
https://github.com/michaella23/bootcamp-collab/pull/77

**Comment by michaella23** [comment]
Cool! Thanks for your quick response.

**Comment by will-s-205** [comment]
Should we close this issue also? Seems like issue solved.

**Comment by michaella23** [comment]
> Should we close this issue also? Seems like issue solved.

Let's leave it for now please. i'd like to hear from Andre after my code review.

**Comment by will-s-205** [comment]
Closing out this issue as done
