### ISSUE TITLE
Label Suggestions

### ISSUE THREAD

**Issue by awcoetzer** [michaella23/bootcamp-collab#80]
Hi @michaella23,

I'm creating this issue to request label suggestions from not only you but also other contributors. It would be great if we could keep this issue open indefinitely.

Here are the labels I had in mind, categorized accordingly:

### UI/UX Labels
- **UI/UX**: This label is for contributors who prefer design over coding. They can showcase their Figma design skills by suggesting ideas for existing components or future design concepts.
    - **UI Design**: Use this label for issues or tasks related to user interface design.
    - **UX Design**: Apply this label to highlight issues or tasks focused on user experience design.
- **Responsive** or **Make Responsive**: This label can be applied to tasks or issues related to making the design responsive.

### Platform/Environment Labels:
- **Web**: Apply this label to issues or tasks specific to web development.
- **Mobile**: Use this label to identify issues or tasks specific to mobile app development.

### Languages Labels
- **Markdown**: Use this label for issues or tasks related to Markdown language.
- **CSS**: Apply this label to issues or tasks specific to CSS.
- **HTML**: Use this label for issues or tasks related to HTML.
- **JavaScript**: Apply this label to issues or tasks specific to JavaScript. These labels distinguish the specific skills required for each issue and help contributors search for problems they would like to solve based on their preferred language.

### Fixes Labels
- **Typo**: Use this label to identify issues or tasks related to fixing typos.
- **Code Review**: Apply this label to highlight issues or tasks focused on code review.

### Status Labels:
- **Open Indefinitely** or **Keep Open**: This label is used when an issue should remain open for an indefinite period.
- **In Progress**: Use this label to indicate that the issue or task is currently being worked on.
- **Needs Review**: Apply this label when an issue or pull request is ready for review by others.
- **On Hold**: Use this label when an issue is temporarily paused or put on hold due to external factors.
- **Currently Working On**: This label is intended for contributors who have opened issues and are actively working on them. It serves as a visual indicator, allowing you to quickly identify the assignee for an issue at a glance. By utilizing this label, we can enhance our workflow efficiency by ensuring that others are aware of ongoing work and can avoid duplicate efforts. It promotes effective collaboration and streamlines the process of addressing issues.

### Priority Labels:
- **High Priority**: This label can be used to highlight critical issues or tasks that require immediate attention.
- **Low Priority**: Use this label to indicate less urgent issues or tasks that can be addressed later.

### Type Labels:
- **New Feature**: Apply this label when suggesting new functionality or features.

### Complexity Labels:
- **Easy**: This label can be used to identify tasks or issues that are relatively simple and require less effort.
- **Medium**: Apply this label to tasks or issues of moderate complexity.
- **Difficult**: Use this label to identify tasks or issues that are challenging or require advanced skills.

### Translation Labels
- **Translate** or **Translation** or **Translated**: This label could be a valuable addition for contributors who speak languages other than English. It could help individuals from non-English-speaking countries showcase their work in their own language when job hunting, enabling them to present their skills to recruiters in a more accessible way. (Note: This is just an idea, and I'm not sure if it's necessary.)

I hope these label suggestions will enhance our issue tracking process. Please feel free to add your input and suggestions as well.

### Recap
List of labels mentioned above:

- UI/UX
- UI Design
- UX Design
- Responsive
    - or Make Responsive
- Web
- Mobile
- Markdown
- CSS
- HTML
- JavaScript
- Typo
- Code Review
- Open Indefinitely
    - or Keep Open
- In Progress
- Needs Review
- On Hold
- Currently Working On
- High Priority
- Low Priority
- New Feature
- Easy
- Medium
- Difficult
- Translate
    - or Translation
    - or Translated

**Comment by michaella23** [comment]
Hey @awcoetzer, great suggestions. Did you come up with all of this yourself? I'm impressed!
Right now, as you may know, only individuals with write access can add labels to issues. I haven't found a workaround for that. I am considering adding maintainers for this repository though, and then they would be able to add labels.
For now, when you create an issue (or if you are looking at existing issues) you can make suggestions for labels to add and I will add them. I will have to create these labels and the pin an issue or something(?) so people can easily see the labels which can be added.

**Comment by awcoetzer** [comment]
> Hey @awcoetzer, great suggestions. Did you come up with all of this yourself? I'm impressed! Right now, as you may know, only individuals with write access can add labels to issues. I haven't found a workaround for that. I am considering adding maintainers for this repository though, and then they would be able to add labels. For now, when you create an issue (or if you are looking at existing issues) you can make suggestions for labels to add and I will add them. I will have to create these labels and the pin an issue or something(?) so people can easily see the labels which can be added.

I would say looking at the insights tab and seeing the active contributors, can be a good indication of who to add, also some of the more experienced students from Scrimba.

Regarding the list, I did a fair bit of research,  I am ashamed to say I stole some ideas from Codecademy contributors section, xD

**Comment by michaella23** [comment]
> I would say looking at the insights tab and seeing the active contributors, can be a good indication of who to add, also some of the more experienced students from Scrimba.

Yes, I have some people in mind who I would add. 🙂 Part of the reason I haven't yet is that I was hoping we would firstly, have more contributors and secondly, those contributors would be submitting PRs on a semi-regular basis.
Trying to think about how we can get more Bootcamp students involved! Maybe by adding more Issues and the labels you've suggested, newcomers would have a better idea of how to get started.

**Comment by michaella23** [comment]
@awcoetzer can I close this issue? We still have access to all this information and can refer to it in other issues and pull requests.

**Comment by awcoetzer** [comment]
@michaella23 Apologies for not replying sooner, I think for yes, most labels are there for now.
