### ISSUE TITLE
create another HTML file

### ISSUE THREAD

**Issue by michaella23** [michaella23/bootcamp-collab#99]
Let's add another HTML file (or files). We will add a link to it in a separate issue. Open to ideas about content. Maybe this will feature projects by bootcamp students? Maybe there will be short blurbs where students talk about their favorite CSS tricks...

**Comment by Pulkitxm** [comment]
Can I get assigned?

**Comment by michaella23** [comment]
@Pulkitxm hi there, thank you for your request. This is a project that we are working on collaboratively in the [Scrimba Bootcamp](https://scrimba.com/bootcamp). We are limiting contributions to current students in the bootcamp at this time.
